export const BLOCK_LABELS: Record<string, string> = {
    heading:        'Heading',
    text:           'Text',
    image:          'Image',
    button:         'Button',
    hero:           'Hero',
    'product-card': 'Product Card',
    coupon:         'Coupon',
    divider:        'Divider',
    spacer:         'Spacer',
    html:           'HTML',
    social:         'Social',
    conditional:    'IF / ELSE',
    survey:         'Survey / Rating',
    timer:          'Timer',
    video:          'Video',
};