import { CustomField } from '@/types/fields';

export const DEFAULT_FIELDS: CustomField[] = [
    // ── System / locked ──────────────────────────────────────────────────────
    {
        id: 'sys-email',
        key: 'email',
        label: 'Email address',
        type: 'email',
        entity: 'contact',
        required: true,
        system: true,
        description: 'Primary email address used for sending campaigns.',
        placeholder: 'user@example.com',
        defaultValue: '',
        options: [],
        order: 0,
        createdAt: '2025-01-01',
    },
    {
        id: 'sys-first-name',
        key: 'first_name',
        label: 'First name',
        type: 'text',
        entity: 'contact',
        required: false,
        system: true,
        description: 'Used in personalisation tags like {{first_name}}.',
        placeholder: 'Alice',
        defaultValue: '',
        options: [],
        order: 1,
        createdAt: '2025-01-01',
    },
    {
        id: 'sys-last-name',
        key: 'last_name',
        label: 'Last name',
        type: 'text',
        entity: 'contact',
        required: false,
        system: true,
        description: '',
        placeholder: 'Johnson',
        defaultValue: '',
        options: [],
        order: 2,
        createdAt: '2025-01-01',
    },
    // ── Custom contact fields ─────────────────────────────────────────────────
    {
        id: 'cf-phone',
        key: 'phone',
        label: 'Phone number',
        type: 'phone',
        entity: 'contact',
        required: false,
        system: false,
        description: '',
        placeholder: '+1 555-0100',
        defaultValue: '',
        options: [],
        order: 3,
        createdAt: '2025-01-15',
    },
    {
        id: 'cf-company',
        key: 'company',
        label: 'Company',
        type: 'text',
        entity: 'contact',
        required: false,
        system: false,
        description: 'Company or organisation the contact belongs to.',
        placeholder: 'Acme Inc.',
        defaultValue: '',
        options: [],
        order: 4,
        createdAt: '2025-01-20',
    },
    {
        id: 'cf-plan',
        key: 'plan',
        label: 'Subscription plan',
        type: 'select',
        entity: 'contact',
        required: false,
        system: false,
        description: 'Current billing plan tier.',
        placeholder: '',
        defaultValue: 'free',
        options: [
            { id: 'opt-free',       label: 'Free',       value: 'free' },
            { id: 'opt-growth',     label: 'Growth',     value: 'growth' },
            { id: 'opt-pro',        label: 'Pro',        value: 'pro' },
            { id: 'opt-enterprise', label: 'Enterprise', value: 'enterprise' },
        ],
        order: 5,
        createdAt: '2025-02-01',
    },
    {
        id: 'cf-birthday',
        key: 'birthday',
        label: 'Birthday',
        type: 'date',
        entity: 'contact',
        required: false,
        system: false,
        description: 'Used for birthday campaign triggers.',
        placeholder: '',
        defaultValue: '',
        options: [],
        order: 6,
        createdAt: '2025-02-10',
    },
    {
        id: 'cf-opted-in',
        key: 'marketing_opted_in',
        label: 'Marketing opt-in',
        type: 'boolean',
        entity: 'contact',
        required: false,
        system: false,
        description: 'Whether the contact has explicitly opted in to marketing emails.',
        placeholder: '',
        defaultValue: 'true',
        options: [],
        order: 7,
        createdAt: '2025-02-15',
    },
    // ── Campaign fields ───────────────────────────────────────────────────────
    {
        id: 'cf-utm-source',
        key: 'utm_source',
        label: 'UTM Source',
        type: 'text',
        entity: 'campaign',
        required: false,
        system: false,
        description: 'Traffic source tag for analytics.',
        placeholder: 'newsletter',
        defaultValue: '',
        options: [],
        order: 0,
        createdAt: '2025-03-01',
    },
    {
        id: 'cf-goal',
        key: 'campaign_goal',
        label: 'Campaign goal',
        type: 'select',
        entity: 'campaign',
        required: false,
        system: false,
        description: 'Primary objective of this campaign.',
        placeholder: '',
        defaultValue: '',
        options: [
            { id: 'g-awareness', label: 'Awareness',   value: 'awareness' },
            { id: 'g-retention', label: 'Retention',   value: 'retention' },
            { id: 'g-upsell',    label: 'Upsell',      value: 'upsell' },
            { id: 'g-winback',   label: 'Win-back',    value: 'winback' },
        ],
        order: 1,
        createdAt: '2025-03-01',
    },
];